# 연결된 예외(chained exception)

- 한 예외가 다른 예외를 발생시킬 수 있음

- 예외 A가 예외 B를 발생시키면 A는 B의 원인 예외(cause exception)

  ```java
  Throwable initCause(Trhowable cause) // 지정한 예외를 원인 예외로 등록
  Throwable getCause()				 // 원인 예외를 반환
  ```

  ![6](https://user-images.githubusercontent.com/86362202/140648165-9c63a6c9-3cc2-4ca6-ae7d-4d2ee979496d.png)

![8](https://user-images.githubusercontent.com/86362202/140648316-4f455938-5c83-4409-8576-0028d5a81a60.png)

### 연결된 예외를 사용하는 이유

- 여러 예외를 하나로 묶어서 다루기 위해서

  

![9](https://user-images.githubusercontent.com/86362202/140651586-9961dc3d-0f9b-4e92-a4ba-d8965d77c789.png)

- checked예외를 uncheck예외로 변경하려 할 때 ( checekd-필수처리,exception / runtimexception-선택처리)

![111](https://user-images.githubusercontent.com/86362202/140651782-9255847f-1c7e-45bb-a96b-e6761f895600.png)

​	오른쪽 중단에 클래스를보면 spaceException이 많이 쓰이고 있다면 상속을 변경하기 어렵다.

따라서 연결된 예외로 바꾼다. RuntimeException 안에다가 SpcaceException을 넣어 RuntimeException이 발생한 것처럼 위장하게 된다.
